### ISSUE TITLE
Inspecio + NPC Variety + Wanderer's Catalogue causes a crash

### ISSUE THREAD

**Issue by SplendidAlakey** [AmyMialeeMods/wandererscatalogue#1]
**MC** 1.19.2
**[Inspecio](https://modrinth.com/mod/inspecio)** 1.6.0
**[NPC Variety](https://www.curseforge.com/minecraft/mc-mods/npc-variety-port)** 2.2.1
**Wanderer's Catalogue** 1.0.0

To reproduce install all 3 mods and hover over the wandering trader's spawn egg in creative menu.

Might be similar to: https://github.com/Queerbric/Inspecio/issues/61 and https://github.com/Queerbric/Inspecio/issues/33.

Removing any of the mods fixes the issue.

Logs: https://gist.github.com/Footage2-Amply-Pounce/0edc4e079ad7941cc73d3883df76740f

**Comment by AmyMialee** [comment]
Do you have any specific config settings? It won't happen for me.

**Comment by SplendidAlakey** [comment]
I do, I disabled food and shulkerbox tooltips in Inspecio, but I just deleted the config to generate a fresh one and it still crashed. Default NPC Variety config. Don't see any config files for your mod.

**Comment by AmyMialee** [comment]
I believe I found the issue but I'm not fully sure how to fix it.
Both this and NPC Variety add new info to Wandering Traders so I'm just gonna ask around to if there's a way to do that better.

**Comment by SplendidAlakey** [comment]
> I believe I found the issue but I'm not fully sure how to fix it. Both this and NPC Variety add new info to Wandering Traders so I'm just gonna ask around to if there's a way to do that better.

No problem, I'll wait :) Will just remove NPC Variety for now.

And I just discovered that spawning wandering traders also causes a crash, in case it matters.

**Comment by AmyMialee** [comment]
Probably the same issue, I'm guessing Inspectio spawns a trader for the
tooltip.

**Comment by AmyMialee** [comment]
closing for now since it's worked for me when testing in 1.0.1
