### ISSUE TITLE
[Fabric] Crash on startup with Charm

### ISSUE THREAD

**Issue by SplendidAlakey** [AmyMialeeMods/wandererscatalogue#2]
**MC** 1.19.2
**FAPI** 0.60.0
**Wanderers Catalogue** 1.0.0
**[Charm](https://www.curseforge.com/minecraft/mc-mods/charm)** 4.2.2

To reproduce simply install the mods and launch the game.

I suspect the crash is related to #1, but this one only happens on Fabric, Quilt for some reason is unaffected. Also this crash happens on startup, unlike #1.

Setting `"WanderingTraderMaps Enabled"` to `false` in Charm's config lets the game start.

Logs: https://gist.github.com/Footage2-Amply-Pounce/fc3de39066c8dea573e432e8dfaa29be

**Comment by AmyMialee** [comment]
should be fixed now in 1.0.2, thanks

**Comment by SplendidAlakey** [comment]
Both issues are fixed, thank you!
